// Mocks generated by Mockito 5.4.6 from annotations
// in ndis_connect/test/widget/screens/dashboard_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i3;
import 'package:ndis_connect/services/analytics_service.dart' as _i4;
import 'package:ndis_connect/services/remote_config_service.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [RemoteConfigService].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemoteConfigService extends _i1.Mock
    implements _i2.RemoteConfigService {
  MockRemoteConfigService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get pointsEnabled => (super.noSuchMethod(
        Invocation.getter(#pointsEnabled),
        returnValue: false,
      ) as bool);

  @override
  String get aiAssistLevel => (super.noSuchMethod(
        Invocation.getter(#aiAssistLevel),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#aiAssistLevel),
        ),
      ) as String);

  @override
  String get badgeVariant => (super.noSuchMethod(
        Invocation.getter(#badgeVariant),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#badgeVariant),
        ),
      ) as String);

  @override
  String get remindersFunctionUrl => (super.noSuchMethod(
        Invocation.getter(#remindersFunctionUrl),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#remindersFunctionUrl),
        ),
      ) as String);
}

/// A class which mocks [AnalyticsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAnalyticsService extends _i1.Mock implements _i4.AnalyticsService {
  MockAnalyticsService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> logEvent(
    String? name, {
    Map<String, Object>? params,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #logEvent,
          [name],
          {#params: params},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void logError(
    String? message,
    StackTrace? stack,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #logError,
          [
            message,
            stack,
          ],
        ),
        returnValueForMissingStub: null,
      );
}
