name: ndis_connect
description: NDIS Connect – Accessible Flutter app for NDIS participants and providers.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

  # Firebase
  firebase_core: ^2.28.0
  firebase_auth: ^4.17.8
  cloud_firestore: ^4.15.8
  firebase_messaging: ^14.8.1
  firebase_analytics: ^10.10.7
  firebase_storage: ^11.6.9
  # firebase_functions: ^4.5.8  # Temporarily disabled - will implement via HTTP calls
  firebase_remote_config: ^4.4.7
  firebase_crashlytics: ^3.5.7

  # UI / State
  provider: ^6.1.2
  get_it: ^7.7.0

  # Accessibility & i18n
  flutter_localizations:
    sdk: flutter
  # intl: ^0.17.0  # Provided by flutter_localizations
  flutter_tts: ^3.8.5
  speech_to_text: ^6.6.0

  # Maps & Location
  google_maps_flutter: ^2.5.0
  connectivity_plus: ^6.0.4

  # Security & Offline
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.4
  encrypt: ^5.0.3
  flutter_secure_storage: ^9.2.2
  local_auth: ^2.1.8

  # Payments
  flutter_stripe: ^10.1.1

  # Media/Sharing
  url_launcher: ^6.3.0
  share_plus: ^10.0.0

  # Visuals & Docs
  fl_chart: ^0.68.0 # More compatible charting library
  timeline_tile: ^2.0.0
  pdf: ^3.11.0

  # Misc
  http: ^1.2.2
  wear: ^1.1.0
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  lints: ^4.0.0
  build_runner: ^2.4.11

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/icons/
