// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApnZHdnV4GcI8sCFRIkjCD8idR0U1BgNg',
    appId: '1:573485849448:web:c5ac0d19f7c3fc2ebd94dd',
    messagingSenderId: '573485849448',
    projectId: 'ndis-connect-91f11',
    authDomain: 'ndis-connect-91f11.firebaseapp.com',
    storageBucket: 'ndis-connect-91f11.firebasestorage.app',
    measurementId: null,
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCD4wGymp3CLS_wvnrlsKV92EuUsBZYPqI',
    appId: '1:669169575872:android:4da2a8f6388dcb5f6b8a25',
    messagingSenderId: '669169575872',
    projectId: 'distributed-inn-419801',
    storageBucket: 'distributed-inn-419801.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'your-ios-api-key',
    appId: 'your-ios-app-id',
    messagingSenderId: 'your-sender-id',
    projectId: 'ndis-connect-prod',
    storageBucket: 'ndis-connect-prod.appspot.com',
    iosBundleId: 'au.ndis.connect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'your-macos-api-key',
    appId: 'your-macos-app-id',
    messagingSenderId: 'your-sender-id',
    projectId: 'ndis-connect-prod',
    storageBucket: 'ndis-connect-prod.appspot.com',
    iosBundleId: 'au.ndis.connect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'your-windows-api-key',
    appId: 'your-windows-app-id',
    messagingSenderId: 'your-sender-id',
    projectId: 'ndis-connect-prod',
    authDomain: 'ndis-connect-prod.firebaseapp.com',
    storageBucket: 'ndis-connect-prod.appspot.com',
  );
}
